Repository Pengxn/go-xn, pull requests merged in 2025-02, with the labels that each got.

#361 Add health check endpoint
  src/route/route.go
Labels: enhancement ✨

#363 Rename and standardize command variable names
  src/cmd/agent.go
  src/cmd/cmd.go
  src/cmd/update.go
  src/cmd/version.go
  src/cmd/web.go
Labels: enhancement ✨, priority 📌, confirmed 👌

#364 ci: update trigger event configuration
  .github/workflows/test.yml
Labels: CI/CD ⚙️, confirmed 👌, Actions :octocat:

#365 Add `NoIndex` middleware for preventing search engine indexing
  src/middleware/robots_noindex.go
Labels: feature 💡

#367 Enhance WebAuthn user credential handling
  src/controller/user.go
  src/lib/webauthn/user.go
Labels: enhancement ✨

#368 Update version variable and command flag usage text
  src/cmd/cmd.go
  src/cmd/version.go
  src/cmd/web.go
Labels: enhancement ✨

#366 Remove `url` that was flagged as deprecated and replace it with `slug`
  src/controller/article.go
  src/model/article.go
  src/route/article.go
  test/sql/article.sql
  test/sql/user.sql
Labels: enhancement ✨, documentation 📑

#370 Release `0.0.3` version
  script/windows/go-xn.iss
  web/assets/js/main.js
  web/humans.txt
Labels: priority 📌, confirmed 👌, release ✅

#371 fix: missing version information for command
  Makefile
Labels: bug 🐞

#348 Implement cloudflare Turnstile server-side validation integration
  src/lib/turnstile/turnstile.go
  src/lib/turnstile/type.go
Labels: feature 💡

#375 fix: match `yaml` file extension with 2-space indentation
  .editorconfig
Labels: bug 🐞

#372 docs: add changelog document
  docs/changelog.md
Labels: enhancement ✨, documentation 📑

#379 Support multi-platform binary self-updates
  src/cmd/update.go
Labels: enhancement ✨

#381 docs: move SECURITY.md file to `docs` directory
  docs/SECURITY.md
  web/security.txt
Labels: priority 📌, confirmed 👌, documentation 📑

#382 docs: add contributor code of conduct document file
  docs/CODE_OF_CONDUCT.md
Labels: confirmed 👌, documentation 📑

#384 docs: update license copyright notice to include other contributors
  LICENSE
Labels: enhancement ✨, documentation 📑

#385 ci: add macOS workflow to improve multi-platform testing and build
  .github/workflows/test.macos.yml
  .github/workflows/test.yml
Labels: enhancement ✨, CI/CD ⚙️, Actions :octocat:

#380 feat: add markdown render support by GitHub API
  go.mod
  src/lib/github/github.go
Labels: dependencies 📦, feature 💡

#388 ci: normalize artifact names using `runner` context variables
  .github/workflows/test.linux.yml
  .github/workflows/test.macos.yml
  .github/workflows/test.windows.yml
Labels: CI/CD ⚙️, Actions :octocat:

#389 Separate windows build artifacts for binary and installer
  .github/workflows/test.windows.yml
Labels: enhancement ✨, CI/CD ⚙️, Actions :octocat:

#390 ci: export platform-related env variables and use them as artifact names
  .github/workflows/test.docker.yml
  .github/workflows/test.linux.yml
  .github/workflows/test.macos.yml
  .github/workflows/test.windows.yml
Labels: enhancement ✨, CI/CD ⚙️, Actions :octocat:

#394 Update build installer output path
  .github/workflows/test.windows.yml
  script/windows/go-xn.iss
Labels: CI/CD ⚙️, Actions :octocat:, build 🗜

#395 Deprecate `dns` package and remove its test files
  src/lib/dns/common.go
  src/lib/dns/common_test.go
  src/lib/dns/dns_test.go
Labels: dependencies 📦, confirmed 👌, 🗑️ deprecated
